### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage-masterserver#1]
Proposed roadmap for the features of the masterserver:
- [x] dedicated servers register at the masterserver
  - [ ] later: "official" servers authenticate via gpg
- [x] the masterserver provides the alive dedicated servers to the client so it can choose
- [ ] the dedicated server is chosen automatically and people are redirected to the server they're gonna play on (matchmaking)
- [ ] the result is transmitted back to the masterserver so it can adjust the player ranks and perform matchmaking the next time

**Comment by simonsan** [comment]
Want to leave this here as a bookmark:
libsodium is a modern, easy-to-use software library for encryption, decryption, signatures, password hashing and more.

https://download.libsodium.org/doc/
